- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/DeleteFileDialogFragment.java
Refers to https://github.com/open-keychain/open-keychain/issues/954
Fixed crash due to "file" scheme in Uri instead of expected "content" scheme by adding a java.io.File delete method using the path of the Uri, inside the "file" part of the deletion.
Broadened the scope of files we can delete by adding the aforementioned java.io.File delete method to the "content" part of the deletion also, which is called in case the ContentResolver fails. This was found to be necessary to delete the file while testing with ES File Explorer. Probably because the ContentProvider on the application we obtain the Uri from did not/refused to handle the delete operation?
> Issue #954 - fixed crash when file scheme is passed, broadened deletion scope

- .gitmodules
...in git
Submodules fix in a separate pull request as suggested by @dschuermann 
Please review. Thanks
> Submodulesfix

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyFinalFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyInputFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SelectPublicKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/ImportKeysAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/SelectKeyCursorAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/UserIdsAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/KeyFormattingUtils.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/CertifyKeySpinner.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/SignKeySpinner.java
Created enum FragAction in CreateKeyActivity.java and enum State in
KeyFormattingUtils.java and replaced int constants with them
> #1042 replaced some int constants with enums

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
Asks Passphrase for key delete/export in ViewKeyActivity.
> Asks Passphrase for key delete/export in ViewKeyActivity.

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/DeleteFileDialogFragment.java
- OpenKeychain/src/main/res/values-cs/strings.xml
- OpenKeychain/src/main/res/values-de/strings.xml
- OpenKeychain/src/main/res/values-es/strings.xml
- OpenKeychain/src/main/res/values-et/strings.xml
- OpenKeychain/src/main/res/values-eu/strings.xml
- OpenKeychain/src/main/res/values-fi/strings.xml
- OpenKeychain/src/main/res/values-fr/strings.xml
- OpenKeychain/src/main/res/values-it/strings.xml
- OpenKeychain/src/main/res/values-ja/strings.xml
- OpenKeychain/src/main/res/values-nl/strings.xml
- OpenKeychain/src/main/res/values-pl/strings.xml
- OpenKeychain/src/main/res/values-ru/strings.xml
- OpenKeychain/src/main/res/values-sl/strings.xml
- OpenKeychain/src/main/res/values-sr/strings.xml
- OpenKeychain/src/main/res/values-sv/strings.xml
- OpenKeychain/src/main/res/values-tr/strings.xml
- OpenKeychain/src/main/res/values-uk/strings.xml
- OpenKeychain/src/main/res/values-zh-rTW/strings.xml
- OpenKeychain/src/main/res/values-zh/strings.xml
- OpenKeychain/src/main/res/values/strings.xml
Please have a look at the updates. I've fixed the handling of adding duplicate files too.
> Updated fix for Issue #1116

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeychainIntentService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeychainIntentServiceHandler.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CertifyKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ConsolidateDialogActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyFinalFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFilesFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptTextFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EditKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysProxyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SafeSlingerActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/UploadKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyTrustFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/DeleteKeyDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ExportHelper.java
Created enums IOType in KeychainIntentService and MessageStatus in KeychainIntentServiceHandler. Fixed  three typos in the aforementioned classes, too.
> #1042: Replaced ints with enums 

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
Possible Fix for Issue #997 
(May revise to hide NFC button instead)
> Check if NFC is available on device

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/AccountSettingsFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/SelectSignKeyIdActivity.java
While trying to fix issue #1123 I came across this one.
> Fixed a ClassCastException

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java
Contact Sync should work on all supported API levels now ^^
> Removed JellyBean restriction on Contact Sync

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/Notify.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ExportHelper.java
Regarding first commit.
This crash occurs when deleting a key with a stripped master key from the
ViewKeyActivity.
> Fixed a crash on ViewKeyActivity and Issue #1114

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/CertifyResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/DeleteResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/ImportKeyResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteServiceActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeychainIntentServiceHandler.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CertifyKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyFinalFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFilesFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptTextActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptTextFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EditKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptTextActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/QrCodeViewActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SafeSlingerActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/FileDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/Notify.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/NfcHelper.java
- OpenKeychain/src/main/res/layout/import_keys_activity.xml
@dschuermann 
The workaround that I made yesterday doesn't seem to work at some places like `ImportKeysActivity`. So I've completely reworked the `Notify` class to keep everything clean and to properly handle the snackbar problem even in the future.
Changes:
* Notifications are created using **Notify.create().show();**
* Overloadings for create()
* create(Activity activity, String text, int duration, Style style, ActionListener actionListener, int actionResId)
* create(Activity activity, String text, int duration, Style style)
* create(Activity activity, String text, Style style)
* create(Activity activity, int textResId, int duration, Style style, ActionListener actionListener, int actionResId)
* create(Activity activity, int textResId, int duration, Style style)
* create(Activity …
> Updated fix for Snackbar behind Keyboard.

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
> #1045: Add a loop for multiple key export.

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysProxyActivity.java
Fix for Issue https://github.com/open-keychain/open-keychain/issues/1198.
It seems that `returnResult` was used to imply two things:
1. Whether the fingerprint should just be scanned and returned (not imported).
2. Whether the activity was started from inside OpenKeychain or externally.
Due to 1., importing a key via QR Code meant `returnResult` was set to false. Due to 2., it incorrectly implied that this was an external request. Since external requests can't be expected to interpret our logs, we were showing a toast.
To separate the two, an extra `EXTRA_IS_INTERNAL` is passed to `ImportKeysProxyActivity` whenever it is started from within OpenKeychain and a log is to be returned.
I've also renamed `returnResult` to `onlyReturnFingerprint` to reflect the difference between the two.
From …
> Make Logs not Toasts - Fixes Issue #1198

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsKeyServerActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/AddKeyserverDialogFragment.java
- OpenKeychain/src/main/res/layout/add_keyserver_dialog.xml
- OpenKeychain/src/main/res/values/strings.xml
Fixes Issue https://github.com/open-keychain/open-keychain/issues/1202.
I've used the `TlsHelper.openConnection()` function to check for connectivity, mainly because sks-keyservers.net (and some other servers, as mentioned in TlsHelper) required it for their hkps/https connections to be verified.
> Verifying Newly Added Keyservers

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptTextFragment.java
- OpenKeychain/src/main/res/layout/encrypt_files_fragment.xml
- OpenKeychain/src/main/res/layout/encrypt_text_fragment.xml
- OpenKeychain/src/main/res/values/strings.xml
Also have a fixed an error message.
> Fixed Snackbar behind layout

- OpenKeychain/build.gradle
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/MainActivity.java
- OpenKeychain/src/main/res/layout/main_activity.xml
- OpenKeychain/src/main/res/layout/main_drawer_header.xml
> Switch to MaterialDrawer library

- README.md
I found that the README was not entirely accurate with respect to the current development status and it took me a while to figure out what I needed to get and do to make it work.
> Update README.md with new build info

- OpenKeychain/build.gradle
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/CreateKeyActivityTest.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/matcher/EditTextMatchers.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyEmailFragment.java
This is my first time writing tests so if I've gone wrong somewhere or left anything important please let me know. Also fixed few minor bugs.
> Espresso test for CreateKeyActivity

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/ImportExportOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
Added:
* Contact sync on key import
* Crash prevention if raw contact for secret key does not exist in 'me' contact
* Delete raw contacts marked for deletion by user
Fixes Issue https://github.com/open-keychain/open-keychain/issues/1260
> Fixed sync on key import, crash for 'me' linked contact

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/ImportExportOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
- OpenKeychain/src/main/res/values/strings.xml
Looked like the logic was in place but we were accidentally replacing the keyserver key with that from kaybase.io, before the merge. Hope I haven't misunderstood anything.
Should solve Issue https://github.com/open-keychain/open-keychain/issues/1310.
> Merge key from Keyserver with that from Keybase instead of replacing

- OpenKeychain/src/main/res/raw/help_faq.md
I had the darnest time remembering my old APG days where something was said in passing about, unlike any other application I know, the need here for OI File Manager (or others, later on) to be able to select local files.  I'm sure I'm not the only person who could benefit from this reminder. :)
> Explicit mention of dependency on 3rd party tool

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/CloudSearch.java
Fixes https://github.com/open-keychain/open-keychain/issues/1161.
> Kill search threads that have not returned

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsActivity.java
Solves https://github.com/open-keychain/open-keychain/issues/1406.
Sorry, I had forgotten to update the submodule.
> Linked normal proxy settings to normal proxy checkbox

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/GetKeyResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateYubiKeyImportFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysProxyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/UploadKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/ImportKeysListCloudLoader.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/orbot/OrbotHelper.java
Should fix https://github.com/open-keychain/open-keychain/issues/1412. Tried making it similar to how CryptoOperationFragment handles it. Should we have something like that for loaders?
> Shifted proxy logic to ImportKeysListCloudLoader

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/ImportOperation.java
Fixes https://github.com/open-keychain/open-keychain/issues/1480 and provides a cleaner solution to https://github.com/open-keychain/open-keychain/issues/1221. 
Issue was due to `mProviderHelper.clearLog()` being called in parallel with `mProviderHelper.savePublicKeyring()` during multi-threaded key import. No wonder it was so hard to reproduce.
> Fixed crash during "update all"

- README.md
Otherwise github related errors occur during the build
> Fix build instruction

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/ContentDescriptionHint.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/LongClick.java
- OpenKeychain/src/main/res/layout/key_list_item.xml
- OpenKeychain/src/main/res/layout/view_key_activity.xml
- OpenKeychain/src/main/res/values/strings.xml
Changed class and string names.
> Issue mouseover hints

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
I just do some changes in OperationResult.java
> Issue#1605 solved

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupCodeFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/HelpActivity.java
- OpenKeychain/src/main/res/layout-land/backup_code_fragment.xml
- OpenKeychain/src/main/res/layout-mdpi/backup_code_fragment.xml
- OpenKeychain/src/main/res/layout-xhdpi/backup_code_fragment.xml
- OpenKeychain/src/main/res/values/strings.xml
I add a link to in-app faq in the backup UI according to the Issue#1595
<a href="https://github.com/open-keychain/open-keychain/issues/1595">https://github.com/open-keychain/open-keychain/issues/1595</a>
> Issue#1595

- .travis.yml
- OpenKeychain/build.gradle
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/CertifyOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/ExportTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/PromoteKeyOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/PgpKeyOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/UncachedKeyringCanonicalizeTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/UncachedKeyringMergeTest.java
- build.gradle
Working on reducing the memory consumption and runtime of our tests
> Fix travis

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeyserverSyncAdapterService.java
Fixes https://github.com/open-keychain/open-keychain/issues/1701. 
Caused by no account being created by the time `isSyncEnabled` was called. The intent was using `ACTION_CANCEL` (used in the `onResume` of `BaseActivity`), and since no Activity could have started before `onCreate` in `KeychainApplication` (<a href="http://developer.android.com/reference/android/app/Application.html#onCreate()">documentation</a>) was called, it looks like `onSyncCancelled` in `KeyserverSyncAdapter` was triggered somehow before `onCreate` completed. Is this possible? 
Either way, this PR should prevent a crash in case an account is not created as expected.
> Prevent Rare KeyserverSyncAdapterService Crash

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ApiPendingIntentFactory.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ApiPermissionHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemotePassphraseDialogActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteSecurityTokenOperationActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateSecurityTokenImportResetFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/PassphraseDialogActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SecurityTokenOperationActivity.java
Awaiting feedback from @Valodim
> Better seperation of remote activities

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/ContactSyncAdapterService.java
Issue: https://github.com/open-keychain/open-keychain/issues/1720
> Contact Synchronisation Notification

- OpenKeychain/build.gradle
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/linked/LinkedTokenResource.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/linked/resources/GenericHttpsResource.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/linked/resources/GithubResource.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/linked/resources/TwitterResource.java
Changed LinkedTokenResource fetResource to okhttp.
Checked for github and tweeter.
> Replaced apache http to okhttp in LinkedTokenResource

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsKeyserverFragment.java
> Fix display of keyserver item in dark theme in SettingsKeyserverActivity

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainDatabase.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/ProviderHelper.java
Save split user ids in database
> WIP: Save split user ids in database #1745

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/Constants.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/receiver/NetworkReceiver.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/ContactSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeyserverSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/res/values/strings.xml
- OpenKeychain/src/main/res/xml/sync_preferences.xml
Final PR, all changes included and tested throughly.
> Sync only when unmetered internet is available #1670

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CertifyKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CertifyKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/MultiUserIdsFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/UploadKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/MultiUserIdsAdapter.java
- OpenKeychain/src/main/res/layout/certify_item.xml
- OpenKeychain/src/main/res/layout/certify_key_fragment.xml
- OpenKeychain/src/main/res/layout/multi_user_ids_fragment.xml
- OpenKeychain/src/main/res/layout/upload_key_activity.xml
> Display Key in UploadKeyActivity Issue #506

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/EditSubkeyDialogFragment.java
- OpenKeychain/src/main/res/values/strings.xml
Based off @tdjogi010's [work](https://github.com/open-keychain/open-keychain/pull/1736), improved on the solution as mentioned in pull request 1736.
Fixes #1554
> Warn when stripping master key #1554

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/res/values/colors.xml
> tint linked contact picture in toolbar #1298

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysFileFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/FileHelper.java
- OpenKeychain/src/main/res/values/strings.xml
This is a solution for:
https://github.com/open-keychain/open-keychain/issues/1673
> Handle encrypted files in "import key" file selection

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/CertifyOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/SignEncryptOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpCertifyOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpDecryptVerifyOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpKeyOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ApiPendingIntentFactory.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/input/RequiredInputParcel.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateSecurityTokenImportResetFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SecurityTokenOperationActivity.java
- OpenKeychain/src/main/res/values/strings.xml
Currently user can sign and decrypt with wrong security token which should not happen.
This PR adds checks before signing and decryption.
> Check security token

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptModeAsymmetricFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/EncryptKeyCompletionView.java
- OpenKeychain/src/main/res/layout/encrypt_asymmetric_fragment.xml
> Add + button besides TokenAutoComplete, Issue #925

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptInputParcel.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/KeyAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/EncryptKeyCompletionView.java
- OpenKeychain/src/main/res/values/strings.xml
> Fix Crash when no encryption subkey is available, Issue #1817

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateSecurityTokenWaitFragment.java
> Fix rotation crash in CreateSecurityTokenWaitFragment #1849

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/ImportKeysListLoader.java
As above, fixes the bug for #1854
> Fixes bug for #1854

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/BackupOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ApiPendingIntentFactory.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/CryptoInputParcelCacheService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteBackupActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/BackupKeyringParcel.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupCodeFragment.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/ExportTest.java
> WIP: Backup API

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java
> SecurityToken: add support for 3072 & 4096bit RSA keys

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/BackupOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/BenchmarkOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/SignEncryptOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/PgpSignEncryptResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptData.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptInputParcel.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/SignEncryptParcel.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptTextFragment.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/PgpEncryptDecryptTest.java
This refactoring is needed for two reasons:
1) Because https://github.com/open-keychain/open-keychain/blob/8b8b91e24722f254ad84916d3e1b6c6210906924/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java#L108
2) Because it's needed to produce good code for my other PR #1760
It's a WIP because it needs a bit more testing, a bit of code clean up and probably tests should be adapted too. This doesn't introduce functional changes. I will continue to work on this during next days. Advices and suggestions are welcome :)
> PgpSignEncryptOperation refactoring

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/res/layout/backup_restore_fragment.xml
- OpenKeychain/src/main/res/layout/encrypt_decrypt_fragment.xml
- OpenKeychain/src/main/res/xml/cloud_search_preferences.xml
- OpenKeychain/src/main/res/xml/passphrase_preferences.xml
> Minor UI improvements and cleanup

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupRestoreFragment.java
> Added passphrase check for stripped masterkeys

- .travis.yml
- OpenKeychain/build.gradle
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/TestHelpers.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/remote/OpenPgpServiceTest.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/ui/AsymmetricFileOperationTests.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/ui/AsymmetricTextOperationTests.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/ui/CreateKeyActivityTest.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/ui/EditKeyTest.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/ui/MiscCryptOperationTests.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/ui/SymmetricTextOperationTests.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareTest.java
- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/ui/widget/EncryptKeyCompletionViewTest.java
I've spent quite some time trying to understand the reason for a lot of proguard errors while trying to start instrumented unit tests. This PR contains an edit to gradle that is necessary to fix the problem. (Probably this is needed because of an upgrade of gradle)
Trying to execute instrumented unit tests, i saw that a lot of them are failing. (Probably because of updates in the code of the app).
If you agree, i will stop a bit from my main task, to spend some time trying to fix all the error in these tests. In this way we will have a good testing enviroment for future developments (mine included).
> Instrumented unit tests: fix for execution

- dependencyci.yml
> ignore deprecated snackbar in dependencyci.yml

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/OpenPgpSignatureResultBuilder.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignatureChecker.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/KeyFormattingUtils.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/PgpEncryptDecryptTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/provider/InteropTest.java
use enums instead of constants, and also add timestamp
this time nicely compatible :)
> Openpgp signature result v4

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
Preparations for work on per-client tofu trust model. There *should* be no semantic changes in this PR.
I changed some api level constants into descriptive feature-based names, and broke down the way pgp results are parsed into result intent into nicely separated methods.
> break down result handling in OpenPgpService into methods

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteSelectPubKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupCodeFragment.java
I originally wanted to redo this entire activity, but that turned out to be more complex than I had thought. This fixes the current dialog instead - I hope :)
> fix loop bug in key selection

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java
what it says on the tin. fixes #1994 I think, but can't really check to make sure. Can you look over this @af-anssi ?
> support odd rsa moduli on security tokens

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/PackageUninstallReceiver.java
> Remove api apps when they are uninstalled

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainDatabase.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/SplitUserIdTest.java
Better handle corner cases of User IDs
Fixes https://github.com/open-keychain/open-keychain/issues/1944 and https://github.com/open-keychain/open-keychain/issues/1699
SplitUserIdTEst
> Better handling of User ID corner cases

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/CanonicalizedPublicKey.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainDatabase.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/ProviderHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/KeyAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/KeySectionedListAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/SubkeysAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/adapter/CursorAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/SignKeySpinner.java
- OpenKeychain/src/main/res/values/strings.xml
Added changes related to insecure keys, as described in #2022 
Import insecure keys manually.
> Display insecure key warnings

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainDatabase.java
At this point everyone should have updated OpenKeychain to a current version...
> Remove AGP db upgrade

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/ImportKeysList.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/ImportKeysListEntry.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/CanonicalizedKeyRing.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/ImportKeysAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/bindings/ImportKeysBindings.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/bindings/ImportKeysExtraBindings.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/EmailKeyHelper.java
- OpenKeychain/src/main/res/layout/import_keys_list_item.xml
- OpenKeychain/src/main/res/layout/import_keys_list_item_extra.xml
Added an insecure warning in the key import card.
#2030 
Imported a insecure key manually.
> Added insecure warning to import card

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/CardCapabilities.java
> Fix NPE in CardCapabilities #2000

- .travis.yml
Travis: use sys-img-armeabi-v7a-android-25
> WIP: Travis: use sys-img-armeabi-v7a-android-25

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/linked/LinkedIdCreateHttpsStep2Fragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/Notify.java
Add missing .show() to some Notify.create() calls.
> Fix showing of some notifications

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/NfcTransport.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnection.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenInfo.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/Transport.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/UnsupportedSecurityTokenException.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/UsbTransport.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/BaseSecurityTokenActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/token/ManageSecurityTokenContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/token/ManageSecurityTokenFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/token/ManageSecurityTokenPresenter.java
- OpenKeychain/src/main/res/layout/create_security_token_import_fragment.xml
- OpenKeychain/src/main/res/values/strings.xml
- OpenKeychain/src/main/res/xml/usb_device_filter.xml
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnectionTest.java
Instead of filtering by the USB xml, we will move to a method of filtering inside OpenKeychain, so we can display helpful messages to the user.
> Change USB filtering

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenInfo.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/UsbTransport.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/token/ManageSecurityTokenContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/token/ManageSecurityTokenFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/token/ManageSecurityTokenPresenter.java
- OpenKeychain/src/main/res/values/strings.xml
* Removes GNUK_UNKNOWN, not used anywhere
* Add support for Nitrokey Start and Storage
Tested with Nitrokey Start and Storage
> Nitrokey Start/Storage Support

- sshauthentication-api/README.md
- sshauthentication-api/src/main/java/org/openintents/ssh/authentication/SshAuthenticationApi.java
> Improve sshauthentication-api documentation

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/HelpActivity.java
- OpenKeychain/src/main/res/raw/help_about.md
- OpenKeychain/src/main/res/raw/help_licenses.md
- OpenKeychain/src/main/res/values/strings.xml
This PR includes the required license texts in-app.
> Include license texts in-app

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/PanicExitActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/PanicResponderActivity.java
@Valodim and @dschuermann asked me to do so, and I said yes.
this originally came from #1683
> change my contributions to Apache-2.0 license

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/OpenPgpCommandApduFactory.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/operations/PsoDecryptTokenOp.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnectionCompatTest.java
This introduces some changes to improve compatibility with weirdly behaving Yubikeys. See #2049 for a discussion.
> Yubi compat

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/Constants.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptTextFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/res/menu/encrypt_file_fragment.xml
- OpenKeychain/src/main/res/menu/encrypt_text_fragment.xml
- OpenKeychain/src/main/res/values/strings.xml
Add options to toggle self-encrypt in both text and files encryption fragment.
See feature request in #2279
> Option self encrypt

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/operations/PsoDecryptTokenOp.java
what it says on the tin. see #2292
> allow other curves than NIST on security tokens

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysProxyActivity.java
This change will extend QR scanner with simple VCard support. When a VCard is scanned it will extract URI from `KEY` field and process it just like it would be a URI scanned directly. When a `openpgp4fpr` URI is put there the UI would search and import the key and show the confirmdialog.
Example VCard with this URI:
BEGIN:VCARD
FN:Test WKD
EMAIL:test-wkd@metacode.biz
KEY:OPENPGP4FPR:74EC8D3DA82A79DAA25DF10C6BA55ED83ABAE1BB
END:VCARD
Currently QR scanner supports only `openpgp4fpr` URIs. VCard specification allows embedding public key information as an URI in [`KEY` field](https://tools.ietf.org/html/rfc6350#section-6.8.1). Two schemes used with this field - `https` and `data` are [either insecure or not practical](https://www.av8n.com/computer/htm/distributing-keys.htm#sec-fing). As the …
> Extend QR scanner to support VCards with KEY field

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/CloudSearch.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/WebKeyDirectoryClient.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/processing/ImportKeysListCloudLoader.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ZBase32.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/util/ZBase32Test.java
If a search pattern that looks like an email address is found
an additional query to Web Key Directory will be performed.
I'd gladly appreciate any feedback!
Fixes partially #2270.
Search for `test-wkd@metacode.biz`, a key that is reachable only via WKD succeeds with this change.
> Search for keys in Web Key Directory

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/compatibility/ClipboardReflection.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptDecryptFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
- OpenKeychain/src/main/res/values/strings.xml
Importing keys from clipboard has been difficult to find for a long time now. This is a simple attempt to fix that problem.
> show Snackbar if clipboard contains key data

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupRestoreFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/res/layout/import_keys_cloud_suggestions_item.xml
- OpenKeychain/src/main/res/menu/export_public.xml
- OpenKeychain/src/main/res/values/strings.xml
What is says on the tin. I used a popup menu for the choice between `file` and `action_send`
> Allow export of public keys without encryption

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/UsbConnectionDispatcher.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/UsbTransport.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/UsbEventReceiverActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/BaseSecurityTokenActivity.java
This PR makes OpenKeychain re-request permission to use USB devices if missing at certain points. This should help the problem that came up in #2366.
> Request missing permission when rescanning USB devices

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/keyview/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ShareKeyHelper.java
- OpenKeychain/src/main/res/layout/view_key_activity.xml
- OpenKeychain/src/main/res/values/strings.xml
Add buttons for sharing a key to primary key view.
See https://github.com/open-keychain/open-keychain/issues/2387
Tested manually.
> Add key sharing buttons to key view

- build.gradle
- sshauthentication-api/build.gradle
Update gradle plugin, harmonizing versions across modules.
Compiles & works.
- ✅ build tools update
> Update android plugin for gradle

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
Fixes saving XMPP URIs in phone Contact Book
Previously XMPP URIs were saved as non functional e-mails in Android built-in Contact Book. This change saves them as a special IM field that is used [directly by other applications](https://github.com/siacs/Conversations/issues/3158#issuecomment-418985376) (e.g. Conversations).
Tested on a real device with a key with UID `xmpp:test@example.com`. After signing that key and synchronizing contacts OpenKeychain created a contact with e-mail field from primary UID and Jabber IM field
Key in OpenKeychain (debug):
Created contact in Phone Book:
> Fix saving XMPP URIs in phone Contact Book

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainDatabase.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/KeyRepository.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/SshAuthenticationService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ssh/AuthenticationOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/keyview/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ShareKeyHelper.java
- OpenKeychain/src/main/sqldelight/org/sufficientlysecure/keychain/Keys.sq
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/AuthenticationOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/ssh/SshPublicKeyTest.java
Fixes https://github.com/open-keychain/termbot/issues/12
> Use specialized query exclusively to select authentication key

- OpenKeychain/src/main/sqldelight/org/sufficientlysecure/keychain/Keys.sq
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/AuthenticationOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/provider/KeyRepositoryTest.java
this broke in #2397, fixed and added a unit test. good thing we're doing betas :)
> fix encryption key selection

- OpenKeychain/build.gradle
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/MainActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SecurityKeyShopFragment.java
- OpenKeychain/src/main/res/layout/security_key_shop_fragment.xml
- OpenKeychain/src/main/res/values/strings.xml
Add a MenuItem to MainActivityDrawer. On Click a the newly added ShopFragments coming up which holds a WebViews that shows the actual shop https://shop.cotech.de/
All revenue from Cotech Security Shop will flow back directly or indirectly to open keychain.
This brings a funding opportunity without a prominent placed donation button.
I've plugged my phone and navigate to the menu item. After click all changes appears to be in a working state.
A Security Key Shop operated by Confidential Technologies GmbH is available within the app.
> Implementation of Cotech Security Keys shop

- OpenKeychain/src/main/res/values/strings.xml
> make autocrypt ad more clear

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SecurityKeyShopFragment.java
> add http referer to shop webview

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenUtils.java
Computes the lengths in the template dynamically according to the mod length when importing RSA keys.
Currently, the lengths of the RSA templates are hard-coded as 0x80 and 0x100, which are the values of RSA 2048.
However, RSA 3072 & 4096 have different values. Therefore, importing keys other than 2048 might be failed.
Fixes the hard-coded lengths in the RSA templates when importing RSA keys to smart tokens.
- ✅ Bug fix
> Computes the lengths in the template dynamically

- build.gradle
> Android Studio 4.1

- extern/MaterialChipsInput/src/main/res/layout/item_list_filterable.xml
- extern/MaterialChipsInput/src/main/res/layout/list_filterable_view.xml
> fix: #2784 #2779 #2402
