- OpenKeychain/build.gradle
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
otherwise we get:
```
:OpenKeychain:compileDebugJava
/home/ligi/git/3rd/open-keychain/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java:686: error: incomparable types: Object and int
if (values.get(UserPacketsColumns.RANK) == 0 && values.get(UserPacketsColumns.USER_ID) == null) {
^
Note: Some input files use or override a deprecated API.
```
> Add ability to compile with java8

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/UserIdsAddedAdapter.java
The App crashed because the Adapter was trying to call a method on a
null object.
Where was the null object?
CheckBox was null because in the Layout file
view_key_adv_user_id_item.xml
There is no such widget with id = user_id_item_check_box
Fix :
I removed the two lines which were causing the bug, and now the screen
loads perfectly.
> Fixes Issue #1081

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
When importing lots of keys, lots of messages about the status of keys
are generated, including some debug slime and general fluff that
isn't really needed a lot of the time. As a result, a serious bug can come
along after key imports or certain operations which cause a log to become
parceled: It gets too big (over the absurd 1Mbit size limit).
This commit implements a pool to "dehydrate" logs into: they are placed
into the pool (a ConcurrentHashMap) and a UUID assigned to them, which
is parceled along. When the OperationResult is un-parceled, it reads in
the appropriate UUID bits and rehydrates the appropriate log.
This avoids the 1Mbit size limit, reducing the parcel down to ~10 bytes,
well under that limit.
In order to avoid any memory leaks, the log pool removes a reference to
the log …
> Fix root cause of #1077

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyInputFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/AddUserIdDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/SetPassphraseDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/EmailEditText.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/PasswordEditText.java
- OpenKeychain/src/main/res/layout/add_user_id_dialog.xml
- OpenKeychain/src/main/res/layout/create_key_input_fragment.xml
- OpenKeychain/src/main/res/layout/passphrase_repeat_dialog.xml
Created EmailEditText extending AutoCompleteTextView with TextWatcher to validate email.
Created PasswordEditeText extending EditText with TextWatcher & Wrapper for PasswordStrengthView.
Implemented them in CreateKeyInputFragment, AddUserIdDialogFragment, SetPassphraseDialogFragment along with required XML changes.
All done in accordance with issue #1106
> EmailEditText, PasswordEditText issue #1106

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyInputFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/SetPassphraseDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/PassphraseEditText.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/passwordstrengthindicator/PasswordStrengthView.java
- OpenKeychain/src/main/res/layout/create_key_input_fragment.xml
- OpenKeychain/src/main/res/layout/passphrase_repeat_dialog.xml
The standalone PassphraseEditText mentioned in PR https://github.com/open-keychain/open-keychain/pull/1075, and now in Issue https://github.com/open-keychain/open-keychain/issues/1106 and PR https://github.com/open-keychain/open-keychain/pull/1107.
The PassphraseEditText has been added to the CreateKeyInputFragment and SetPassphraseDialogFragment.
Screenshots:
> Passphrase strength indicator

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
Refers to https://github.com/open-keychain/open-keychain/issues/1120
Added CALLER_IS_SYNCADAPTER query parameter, with value "true", to all deletion queries. This causes the RawContact to be actually wiped when deleted instead of just the "delete" flag being set. Solves the aforementioned issue of re-imported keys not being linked to system contacts.
> Fixed contact deletion Issue #1120

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/CertifyOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
Fixes https://github.com/open-keychain/open-keychain/issues/1125 and https://github.com/open-keychain/open-keychain/issues/1126. 
TODO: cause displayed system contact to be updated on confirmation of a key from KeyViewFragment, possibly by introducing a cursor returned by loader methods for system contact information, which would allow automatic updating on change in the contacts table?
> Sync only confirmed keys and change 

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
Refers to https://github.com/open-keychain/open-keychain/issues/958
Own keys have been linked to the "me" contact and the linked system contact code has been updated to handle this. Tested it and seems to be working :)
Some functions added like insertMainProfileRawContact, getMainProfileMasterKeyIds and deleteMainProfileRawContactById have resulted in a certain amount of code duplication since they only differ from their normal RawContact counterparts by the Uri being queried. Should we create a base function which these functions call by passing different Uris?
> Own keys linked to "me" contact

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/SignEncryptOperation.java
Please use files of size 1mb+ while testing so that the progress can be viewed clearly.
This fixes enables the change of progress for both Encryption of Files(with and without ASCII armor) and Text.
> Fix for Issue #1115

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
Removed unnecessary @TargetApi(Build.VERSION_CODES.JELLY_BEAN) by calling the query() function which does not accept a cancellation signal (API level 1), since we don't use it anyway.
> Removed unnecessary @TargetApi annotation in ContactHelper

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/ImportKeysList.java
Previously, the cloud key search showed either a keyserver email or a keybase ID as the user's main email, depending on which server request was answered faster.
Now results returned from HKP keyservers will be sorted in front of keybase IDs to show the correct email address in the dialog.
> Show HKP server results first in key cloud search. Fixes #1066

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
When the list of key is long, the Floating Action Button blocks the content of the last few rows. A blank footer (with height `72dp`) is added to the bottom to prevent this (and to follow the [Material Design's Guidelines](http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button): *the content should have enough padding at the bottom so the button does not block content in last row.*)
Before & After:
> Added a blank footer view to the list of keys

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptTextActivity.java
This is a fix for #1173.
During comparison of the two passphrase fields, the activity passphrase is set to null, if the two fields do not match. This causes an issue when entering the second character, at which point the `removeFromMemory()` method is called on the null passphrase. 
An empty passphrase would have been an elegant solution, but the input validation logic expects the passphrase to be null if the inputted passphrases do not match. So a simple null check in the setter will have to do.
> Fixed symmetric encryption crash

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/ImportExportOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/CloudImportService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeychainIntentService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/ServiceProgressHandler.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CertifyKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ConsolidateDialogActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyFinalFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFilesFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptTextFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EditKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysProxyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SafeSlingerActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/UploadKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyTrustFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/DeleteKeyDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/ProgressDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ExportHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ParcelableFileCache.java
- OpenKeychain/src/main/res/menu/key_list.xml
- OpenKeychain/src/main/res/values/strings.xml
Added:
1. Support for multi-threaded key import when importing from the cloud.
2. An "Update all keys" option in the overflow menu of KeyListFragment.
This was just a quick patch I tried it to see how many threads we could run at a time while importing keys from the cloud. I've used a CachedThreadPool limited to 200 threads as of now, and there seemed to be no issues refreshing 174 keys.
I've introduced the multi-threading in KeychainIntentService currently - which I guess isn't a good idea since IntentServices are not really meant to spawn more threads, as the service dies as soon as it has no more work to do. The spawned threads talk back to the activity via the callbacks, but allowing the "Cancel" intent from the activity to reach the spawned threads required making the AtomicBoolean …
> Multi-threaded key import, update all feature

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java
This is due to `input.getSignatureSubKeyId()` (which is a `Long`) can be `null`. 
`result.setNfcData` tries to cast the `null` into a primitive `long` and thus this error appears: `Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference`.
Fix: If the value is `null`, return `PgpSignEncryptResult` with `PgpSignEncryptResult.RESULT_ERROR` as the `result`.
> Fixed #1152: NullPointerException when signing with YubiKey

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/ImportKeyResult.java
If an import operation for multiple keys fails for all, we get an incorrect "Import of %d keys failed!" message. Just had to add a missing parameter.
For reference:
Old:
New:
A comment recommended switching to the warning style in case some keys succeed but others fail. Changed that too.
> Corrected import error message, changed style to WARN

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
- OpenKeychain/src/main/res/layout/view_key_fragment.xml
Changes:
1. Shows linked contact card immediately on key verification.
2. Fixed issue with contact picture not being displayed on older devices (due to lookupUri) (tested on API level 15, http://stackoverflow.com/a/21214524/3000919).
3. Provides a fix for Issue https://github.com/open-keychain/open-keychain/issues/1176 (hide linked system contact card), which is contained to `ViewKeyFragment` and does not require changes to the enclosing activity.
> Immediate display of contact card, fixed contact picture display issue, hides card if no contact

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/BaseNfcActivity.java
According to the OpenPGP spec, PW1 must be submitted with mode 81 for a signing operation, and mode 82 for everything else. OpenKeychain currently verifies the PW1 with mode 82 all the time. OpenPGP-compliant cards will not issue a signature when the PW1 is submitted with mode 82. 
The reason this hasn't been broken is that the only widespread OpenPGP device with NFC, the Yubikey NEO, had a bug that allowed signatures to be generated without a verified PIN. Yubico has fixed this bug as of today, and issued [a security advisory](https://github.com/Yubico/ykneo-openpgp/blob/master/doc/SecurityAdvisory%202015-04-14.txt). New Yubikeys NEO will throw an error when signing is attempted after VERIFY PW1 with mode 82. 
This patch moves the PIN verification from the …
> Fix for NFC signing operations: move PIN verify inside sign/decrypt operation and set correct mode.

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyYubiImportFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysCloudFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/ImportKeysListLoader.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/res/values/strings.xml
Takes care of Issue https://github.com/open-keychain/open-keychain/issues/1199.
It's been written to handle all keyserver URLs based on the presence of /pks/lookup in the path, as specified in http://tools.ietf.org/html/draft-shaw-openpgp-hkp-00#section-3, not just https://hkps.pool.sks-keyservers.net or the ones the user has added on Openkeychain.
I've enabled searching through keybase.io by default when we handle a keyserver search from a URL.
A possible addition would be:
When the user clicks on a URL and it's a keyserver he hasn't registered on Openkeychain yet, we offer the option to add it to his list of keyservers.
> support for handling keyserver urls from browser, added documentation

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/BaseNfcActivity.java
This change adds three fields to BaseNfcActivity to track PIN verification. Two booleans track whether the PIN is verified for a given operation, and a third tracks whether the PIN must be resubmitted for every signature operation (page 32 of OpenPGP smart card spec). It also adds a method to query the PW status bytes for this information. 
This pull request also incorporates a separate commit with an unrelated fix when selecting the application. A successful SELECT FILE operation is indicated by the response ending with 9000, not being equal to 9000 (page 31 of OpenPGP smart card spec). The standard OpenPGP card includes file control information in the returned data field; this change is necessary to accommodate cards that implement this part of the spec.
> Maintain client-side state for PIN verification operations

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysListFragment.java
Should have been keyserver == null instead of keysever != null. Sorry.
Much thanks to @josecastillo for pointing that out.
> Corrected possible null pointer with key import

- OpenKeychain/build.gradle
Since the latest version of library MaterialDrawer depends on latest com.android.support:appcompat version 22.1.0 and we switched to new support lib version 22.1 now, we can update this library to the latest.
> update lib MaterialDrawer to latest(2.8.2)

- OpenKeychain-Test/build.gradle
Fixes #1239 
Updated robolectric also requires explicit import of maven-ant-tasks, otherwise this error results:
java.lang.NoClassDefFoundError: org/apache/maven/artifact/ant/DependenciesTask
> updated robolectric to support new android support libs

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/res/values/strings.xml
Prevents a non-cancelable  progress dialog from appearing if the "Import selected keys" button is pressed after either a cloud search or import from file is performed, but no key is selected.
> Prevent NaN Progress Dialog on import with no selected keys

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
If the activity is killed, and then resumed, `savedInstanceState` will not be null, but the fragment reference will be, causing a `NullPointerException` at `mListFragment.loadNew` on search.
> Prevent NullPointerException due to Activity death

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/UncachedKeyRing.java
Fixes https://github.com/open-keychain/open-keychain/issues/1365. Key query had fingerprint in caps but we use lower case internally.
> Fixed fingerprint mismatch on web download of keys

- OpenKeychain/src/debug/res/values/strings.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/Constants.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/WorkaroundBuildConfig.java
That way debug builds can be distinguished from the release version by name as well.
Also a minor refactoring, explicitly importing "R" an "BuildConfig" by FQN where that wasn't the case.
> Add debug app name

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/CryptoOperationFragment.java
Infinite recursion. Terrible mistake. Should fix https://github.com/open-keychain/open-keychain/issues/1388.
> Fix CryptoOperationFragment infinite recursion

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsKeyserverFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/res/values/strings.xml
Fixes https://github.com/open-keychain/open-keychain/issues/1398.
I've made it accept already existing empty keyserver preferences (in case someone updating has 0 keyservers), but it won't let you delete if you have only 1 keyserver. Having 0 keyservers was unchecked in all places where `getPreferredKeyserver` was being used. Since we were shifting to "at least 1 keyserver", I've left them that way, is that okay?
> Fixe Keyserver Preference crash on empty list

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/ImportOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysProxyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/CryptoOperationHelper.java
I wasn't able to exactly reproduce https://github.com/open-keychain/open-keychain/issues/1425 - my issue was related to when Tor was selected for proxy but wasn't running. A related issue is that selecting "Don't Use Tor" will result in the key being imported and the user taken to the certify screen, but no progress dialog being displayed. Looking into that too.
> Fixed QR code import and serialKeyImport progress

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/HkpKeyserver.java
`HkpKeyserver` now verifies that the upload succeeded. Earlier it was failing uploads only if there was an `IOException`. Does this help with https://github.com/open-keychain/open-keychain/issues/1436?
> Check upload response code and throw AddKeyException

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyTrustFragment.java
- OpenKeychain/src/main/res/values/strings.xml
-No longer appends the links to the keybase_narratives
-Now uses '%s' to insert the names in the keybase_narratives
-added '%s' to keybase_narrative_* in the string.xml file
-- NOTE:Have not modified for other languages
> ISSUE #1304: Change keybase strings 

- OpenKeychain/src/main/res/drawable/fab_label_background.xml
- OpenKeychain/src/main/res/drawable/section_header_dark.xml
- OpenKeychain/src/main/res/drawable/section_header_light.xml
- OpenKeychain/src/main/res/values/attrs.xml
- OpenKeychain/src/main/res/values/styles.xml
- OpenKeychain/src/main/res/values/themes.xml
Fixes https://github.com/open-keychain/open-keychain/issues/1470
According to http://stackoverflow.com/questions/8041537/how-to-reference-style-attributes-from-a-drawable/13471695#13471695, drawables can't refer to an attribute. The workaround implemented from there involves having a separate drawable xml for each theme. 
Changed all the drawables I could find that do this (as tracked down from a usage search of items in attrs.xml). Hope that covers everything.
> Fixed crash on api < 21 due to drawable using attrs

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/OrbotRequiredDialogActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsKeyserverFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyTrustFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/AddEditKeyserverDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/OrbotStartDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/SupportInstallDialogFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ParcelableProxy.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/orbot/OrbotHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/orbot/TorServiceUtils.java
- OpenKeychain/src/main/res/values/strings.xml
Adds silent start and resuming of interrupted operation after Orbot is started (earlier the user had to trigger the action again). Falls back to a dialog if the user has disabled silent start. Would come in handy for Keyserver sync (https://github.com/open-keychain/open-keychain/pull/1461).
> Updated OrbotHelper with the latest NetCipher

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/ImportOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeyserverSyncAdapterService.java
In `KeyserverSyncAdapterService`:
* Ignore null Intents and Intents with null actions to fix https://github.com/open-keychain/open-keychain/issues/1573.
* Introduced `START_REDELIVER_INTENT` to better handle service process being killed.
* Modified staggered Orbot update so that the first key is updated immediately. A large time difference between when Orbot is started and when the key is updated could result in starvation if the user turns Orbot off before even a single key could be updated (besides repeated Orbot starts and a lengthier update).
In `ImportOperation`:
* Corrected case where an early cancellation of multi-threaded import may be interpreted as `RESULT_FAIL_NOTHING`.
> Reworked KeyserverSyncAdapterService

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/CloudSearch.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/FacebookKeyserver.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/ImportKeysList.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/ImportKeysListEntry.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/KeybaseKeyserver.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/Keyserver.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/ParcelableKeyRing.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/ImportOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeyserverSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateYubiKeyImportResetFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysCloudFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysProxyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/EmailKeyHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/res/values/strings.xml
- OpenKeychain/src/main/res/xml/experimental_preferences.xml
- OpenKeychain/src/main/res/xml/passphrase_preferences.xml
Related to https://github.com/open-keychain/open-keychain/issues/1321
This PR adds:
* Support for importing keys from links of the form:
https://www.facebook.com/*/publickey/download.
e.g. https://www.facebook.com/adithya.abraham/publickey/download <br>
Requirement: The visibility of the key must be set to "Public" on Facebook.
* Reloading of `ImportKeysActivity` if the activity was already open and a new Intent is received.
Testing Facebook search:
* Clicking on above link in browser (after which you may search for any Facebook username) (or)
* Add https://facebook.com as preferred keyserver (this works because of the URL inspection mentioned below) and searching for a person's Facebook username.
A query to Facebook is currently identified in `CloudSearch` and `ImportOperation` by URL …
> Basic Facebook Support

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/ContactSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeyserverSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsActivity.java
Fixes https://github.com/open-keychain/open-keychain/issues/1622. Looks like at some point keyserver sync and contact linking was enabled whenever the app started.
Also cancels a postponed/staggered sync if it was scheduled, but was disabled in preferences before it could trigger.
> Fixed Keyserver and Contact Sync turning itself on

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/Constants.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/EditKeyOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/PassphraseCacheService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/input/RequiredInputParcel.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupRestoreFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/PassphraseDialogActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsCacheTTLActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsCacheTTLFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/CacheTTLSpinner.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/res/layout/encrypt_asymmetric_fragment.xml
- OpenKeychain/src/main/res/layout/passphrase_dialog.xml
- OpenKeychain/src/main/res/layout/settings_cache_ttl.xml
- OpenKeychain/src/main/res/layout/settings_cache_ttl_fragment.xml
- OpenKeychain/src/main/res/layout/settings_cache_ttl_item.xml
- OpenKeychain/src/main/res/layout/simple_item.xml
- OpenKeychain/src/main/res/values/arrays.xml
- OpenKeychain/src/main/res/values/strings.xml
- OpenKeychain/src/main/res/xml/passphrase_preferences.xml
Using different caching times at different times is quite the valid use case. If I know I'll be doing a lot of keysigning or mail reading in the next hour or so, for example, it should be in the few hours range. Otherwise, couple minutes is fine. But it really varies.
Another advantage is that it raises awareness that passwords are cached. Users are sometimes confused why they aren't asked their password on a second operation, if they havn't noticed the cache notification before.
> Select time to remember password in dialog

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
Fixes https://github.com/open-keychain/open-keychain/issues/1664. Caused due to `handleActions` in `onResumeFragments`.
> Fixed File Import issue due to onResumeFragments

- OpenKeychain/build.gradle
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/BaseSecurityTokenNfcActivity.java
- build.gradle
[Nordpol](https://github.com/fidesmo/nordpol) is a library that tries to consolidate the two different ways Android interacts with NFC as well as well as provide good default values for apps that require real ISO APDU communication with the tag. On top of this provides some work arounds for some of the NFC bugs out there. It tries to do so while being a drop in replacement for the IsoTag class.
I have tried to minimize the changes to the existing code. The following have been altered:
- Replace handling of intents with Nordpol tag dispatcher
- Update CreateKeyActivity to pass it's intent to the tag dispatcher
when invoked by the system (onCreate)
- Add Fidesmo marmeladburk repository
- Add dependency on nordpol-android and nordpol-core
> Use Nordpol for BaseNfcActivity

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/BaseSecurityTokenNfcActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/FidesmoInstallDialog.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/FidesmoPgpInstallDialog.java
- OpenKeychain/src/main/res/values/strings.xml
Handles the case of a PGP applet not being available on a (possibly) compatible Security Token.
If the Security Token is a Fidesmo device it prompts the user to install the applet through the Fidesmo app. If the Fidesmo app is not installed the user is prompted about that.
> Handle not installed PGP applet

- .gitmodules
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/UncachedKeyRing.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/provider/InteropTest.java
Unlike UID revocations which are "reversible" by newer UID
self-signatures, a subkey revocation should be "permanent" even if
followed by a newer self-signature.
The RFC is ambiguous on this, but this is the convention used by (e.g.)
GnuPG. The rationale for this behaviour is available as comments within
the GnuPG source.
UID signatures:
https://github.com/mtigas/gnupg/blob/50c98c7ed6b542857ee2f902eca36cda37407737/g10/getkey.c#L1668-L1674
Subkey signatures:
https://github.com/mtigas/gnupg/blob/50c98c7ed6b542857ee2f902eca36cda37407737/g10/getkey.c#L1990-L1997
> Always revoke subkeys with a revocation signature.

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ExitActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/PanicResponderActivity.java
We've been developing "panic button" features in our apps for years, and now we are working to make a more flexible and open ecosystem of apps that can both trigger other apps, or respond to triggers. Since OpenKeychain already caches passphrases and includes a "clear" feature, it is a natural panic responder app. This setup allows for easy configuration of a single trigger action which can then trigger multiple apps.
The first commit adds support for receiving the panic trigger. The second commit wipes OpenKeychain from the Recent Apps when it is responding to a panic trigger.
I made a video to demonstrate the user experience, this pull request offers the same user experience as the demonstration with Orweb:
https://www.youtube.com/watch?v=mS1gstS6YS8
The first panic button app that …
> allow "panic button" apps to clear all passphrases

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/ContactSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/BaseActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
Fixes https://github.com/open-keychain/open-keychain/issues/1712. Deletes linked contacts in both situations:
* __When the user disables contact linking in the app__ - Linked contacts are immediately deleted.
* __When the user disables contact linking in permissions__ - Linked contacts are deleted the next time any of our activities are resumed. (Wasn't able to find a way to be notified of a change in sync settings except with a <a href="http://developer.android.com/reference/android/content/ContentResolver.html#addStatusChangeListener(int, android.content.SyncStatusObserver)">`SyncStatusObserver`</a> whose implementation seems to require having an always running service).
> Deletes linked OpenKeychain contacts if sync is disabled

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/ApiDataAccessObject.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainExternalContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/ProviderHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/SimpleContentResolverInterface.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ApiPermissionHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/KeychainExternalProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/AccountSettingsActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/AppSettingsActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/AppSettingsAllowedKeysListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteCreateAccountActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteRegisterActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/SelectSignKeyIdListFragment.java
To display contact info in K-9, I needed some way to get data per email address. The straightforward approach is adding a Provider in addition to the OpenPgpService we offer, so that's what I went with.
This is still missing a permission check. I checked and it's possible to check the calling uid just like with other service calls, so it's easy to restrict to apps which are already allowed.
> provider for OpenPgpApi

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupCodeFragment.java
Backup functionality was broken because of a wrong comparison of the backup code. 
Save the string as it's used more than one time.
> Fix backup code comparison

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/InputDataOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/TemporaryFileProvider.java
Some behave strangely when opening files after decryption because they have no name. 
(Ex: Adobe Reader crashes)
Fix it by setting the correct name after decryption.
> Fix wrong behavior of third-party apps while opening files after decryption

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysListFragment.java
This solve a wrong "File not found" when the user try to import a key when the app was not granted read permission previously. (Using Android 6.0)
Allow the user to grant read permission even in this case.
This is a quick fix.
Probably the code here need a bit of refactoring. 
If you agree i will try to restructure it a bit in the future.
> Always check read permission

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesFragment.java
Uri should be removed from pending even when it was already added.
Otherwise we are stuck and can not add new files anymore.
> Fix duplicate file insertion while encrypting

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupCodeFragment.java
For #[1779](https://github.com/open-keychain/open-keychain/issues/1779),
A provisional fix is made to make selection more difficult. Preventing selection altogether is not possible due to the internal implementation in the Masked-Edittext dependency.
To be updated when Masked-Edittext fixes this bug.
> Provisional backup-code text selection fix

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeyserverSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
Until now the only way to update sync interval was uninstalling/re-installing the app. Shouldn't have affected any of our release builds since we never changed it.
> Update Keyserver Sync if Sync Interval Changed

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/CertifyKeySpinner.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/SignKeySpinner.java
In CertifyKeySpinner and SignKeySpinner item at position 0 will not be "none" entry because they are inner adapters. Please see KeySpinner.java:156. That's why even if the first key is revoked or didn't have a signing subkey it is selectable because it consider them as "none" entries.
> Fix Unusable signing key not properly disabled, Issue #1468

- OpenKeychain/src/main/res/values/strings.xml
Not sure about other languages though. I assume they should be fixed via transifex, right?
> Add missing keyholder string param

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptFilesFragment.java
To reproduce it:
1.  Select a file to encrypt
2.  Click on the save icon
<< Now user might realize that he selected the wrong file to encrypt So, he/she will cancel it (don't save) >>
3.  Remove file
4.  Select correct file
5.  Save it
But it will still encrypt the previous file from cache.
> Fix Wrong file encrypted from cached input

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/KeyRing.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyEmailFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyFinalFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateKeyNameFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/EmailEditText.java
- OpenKeychain/src/main/res/layout/create_key_final_fragment.xml
- OpenKeychain/src/main/res/values/strings.xml
Allows an empty name on key generation and does not enforce email formats by regex matching. Instead, it shows a warning in the CreateKeyFinalFragment if an email does not match the regex. The explanation is only shown when the email field was clicked on, to not hide the sync option.
relevant issue: #1825
> Handle user input on key creation more generously

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/KeyRing.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainDatabase.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/SplitUserIdTest.java
When a key has a user id only consisting of an email, that email is wrongly taken as name.
fixes #1699
> Correctly handle keys only having an email address

- OpenKeychain/src/androidTest/java/org/sufficientlysecure/keychain/remote/OpenPgpServiceTest.java
just a small change to make sure the test is using the "new" service
> in OpenPgpServiceTest, use new service interface instead of deprecated old interface

- OpenKeychain/build.gradle
See http://stackoverflow.com/questions/27909613/cannot-see-parameter-value-in-android-studio-when-breakpoint-is-in-first-line-of
Very annoying.
> Add new build type to mitigate debugging issues

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DisplayTextFragment.java
Wanted to send a link and noticed that in our text view activity, links weren't auto-linkified.
There is some room for discussion here: At the moment, I only linkify text if it comes with a valid signature, both confirmed and unconfirmed. We could handle this more strictly (only valid+confirmed) or less strictly (all non-error states), there probably isn't a perfect decision here
> auto-linkify text in DisplayTextActivity, if data is signed

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/processing/ImportKeysOperationCallback.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/processing/ImportKeysResultListener.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/ImportKeysAdapter.java
the way `mCurrent` was used simply wasn't capable of handling multiple processes at once. proposed fix
> fix loading of multiple keys simultaneously

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpServiceKeyIdExtractor.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/remote/OpenPgpServiceKeyIdExtractorTest.java
This PR extracts the key logic ("which encryption keys to use, given a bunch of extras, possibly returning a pending intent for user interaction") from OpenPgpService into its own, testable class - and adds tests for it! Woop woop.
Also fixes #1990
> Move key extraction logic into its own class

- OpenKeychain/src/main/res/values/strings.xml
I feel like this version sounds more natural. If you disagree, feel free to decline the PR. :smiley: 
(Also, see [this chart](https://books.google.com/ngrams/graph?content=this+information+can%2C+these+information+can&case_insensitive=on&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Cthis%20information%20can%3B%2Cc0%3B%2Cs0%3B%3BThis%20information%20can%3B%2Cc0%3B%3Bthis%20information%20can%3B%2Cc0%3B.t4%3B%2Cthese%20information%20can%3B%2Cc0%3B%2Cs0%3B%3BThese%20information%20can%3B%2Cc0%3B%3Bthese%20information%20can%3B%2Cc0) on Google Ngram viewer.)
> Update English message for security_token_reset_or_import

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/CachedPublicKeyRing.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/adapter/SelectEncryptKeyAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/adapter/SelectSignKeyAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DeleteKeyDialogActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/MultiUserIdsFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/CertSectionedListAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/KeyAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/KeySectionedListAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/UserAttributesAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/UserIdsAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/adapter/CursorAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/ContactHelper.java
#1846 
replaced some splitUserId that could be taken place directly by the new database columns.
seems that the other occurrences of splitUserId are irrelevant to database, e.g. The way to import key from clipboard is retrieving userId at first, and then get name etc by splitUserId. How should I deal with them?
> [WIP] replaced some splitUserId (#1846)

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainExternalContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/KeychainExternalProvider.java
This commit introduces a temporary table to KeychainExternal provider.
This is used to return a result set that contains the exact query as identifying column, rather than the matching user id. This is helpful because we match case insensitively internally, while the querying implementation might wish to map search results against verbatim search strings.
The available projection columns are now address, status, and user id. If the client queries only address and status, they will be grouped into the best available verification status. Otherwise, it will be one verification status per user id (which is what K-9 does at the moment).
Related to #1935
> externalprovider: use temp table for query

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/PgpSignEncryptResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptInputParcel.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/res/values/strings.xml
- Added fields for storing allowed keys and indicating that a disallowed key was used.
- Assigned the fields to related values in the API Service
- Added the checks in the related Operation file
For #1830 
> API: Restrict secret keys for sign operation

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/BackupOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/BackupKeyringParcel.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/BackupCodeFragment.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/BackupOperationTest.java
Added a new instance variable mEnableAsciiArmorOutput to BackupKeyringParcel and updated it's usages.
For #1856
Replacing #2017 
Created a backup with and without ASCII armor using the Backup screen in the app and opened the file to verify it's contents.
> Backup API, implement EXTRA_REQUEST_ASCII_ARMOR

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainDatabase.java
Unfortunately, for some people the current upgrade crashes and left them with all keys being insecure. This issue shouldn't have something to do with the new insecure checks, instead it looks like some sort of problem when updating the database in the consolidate dialog.
> emergency fix for crashing consolidate

- OpenKeychain/src/main/res/layout/view_key_adv_certs_header.xml
Fix transparent header in ViewKeyAdvCertsFragment
When working on #1957 , I found that the header in ViewKeyAdvCertsFragment is transparent
Before modification:
After modification:
> fix transparent header

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenUtils.java
Improved handling of RSA modulus length in SecurityTokenUtils.
The code was containing hard coded values for 2048 bits RSA modulus length. This patch fixes this by extracting the size of the RSA modulus from the RSAKeyFormat parameter.
Fix #2036 
Tested only with 2048 bits RSA.
> Fix IllegalArgumentException in SecurityTokenUtils #2036

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/MultiUserIdsFragment.java
Add a null safety check before calling the `String#equals` method.
There is a crash whenever the `lastName` variable happens to be null.
This is documented inside issue #2044 
Tested the changes on Travis CI. The build passes.
[Build #1](https://travis-ci.org/icyflame/open-keychain/builds/203469302) (First draft of the commit message)
[Build #2](https://travis-ci.org/icyflame/open-keychain/jobs/203541336) (Present commit)
> Fix crash inside MultiUserIdsFrag because of null lastName

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainExternalContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/KeychainExternalProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpServiceKeyIdExtractor.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/remote/KeychainExternalProviderTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/remote/OpenPgpServiceKeyIdExtractorTest.java
This PR unifies the way key lookup (user id -> key id) is done. This affects primarily OpenPgpServiceKeyIdExtractor, which previously had its own logic, but now queries the external provider for key ids instead.
This PR *also* introduces EXTRA_DRY_RUN, which causes a SIGN_ENCRYPT operation to abort once all input parameters are determined, and returns a status of keys that would be used in the process. This change is quite simple and isolated in a commit of its own.
> Use KeychainExternalProvider for resolving encryption keys in api

- OpenKeychain/src/main/res/raw/help_faq.md
Replaced singing with signing
I have replaced the incorrect word 'singing' to 'signing'
Previously singing was present in the text.  I corrected this to signing.
Correct spelling helps make the program look more professional.  I use this on a regular
basis and I want to help make it better.
Plain-text change that doesn't require recompilation to test.
Text change (non-code) change.
> TYPO: singing replaced to signing

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/PassphraseCacheService.java
Super small PR: This sets the notification priority for our passphrase cache service to "min", which (at least on my phone) hides the notification from the lock screen and also the icon bar on top.
This seems appropriate to me, given we require no attention whatsoever from the user. And from what I can tell, it doesn't mess with foreground status of the service.
> set cache notification to low priority

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/OpenPgpCapabilities.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java
Temporary workaround to fix issue #2049.
The temporary workaround proposed does not rely only on the "secure messaging" bit from the "extended capabilities", but also on the "secure messaging key size" declared in the "extended capabilities" to trigger on SmartPGP secure messaging only if secure messaging is configured for AES (appeared in specification v3) and not DES.
A regression with OpenPGP applets other than SmartPGP that support secure messaging was introduced by commit a6b7b2bf4ec204cd647db9f0bead53476069d34f, including Yubikey NEO (issue #2049).
No test as been done on Yubikey NEO to verify the issue is fixed.
> fix issue #2049

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/OpenPgpCapabilities.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SCP11bSecureMessaging.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java
OpenPGP card specification v3.3 introduces a bit for secure messaging using SCP11b. It should now be used to avoid any conflict with the AES secure messaging described in the specification.
Use the correct secure messaging type to trigger SCP11b establishment.
As the AES key sizes cannot be inferred from the secure messaging type, they are now fixed and determined by the size of the field of the curve used for secure messaging, as recommended in SCP11 specification.
Correction of the existing workaround which can trigger a SCP11b establishment while the token is not supporting it.
Tested on SmartPGP version 1.3 with SCP11b enabled.
Should not impact other cards (the value 03 for the secure messaging type was unused until OpenPGP card v3.3).
- ✅ Bug fix (non-breaking change which fixes an …
> Update SecureMessaging/SCP11b wrt OpenPGP card v3.3

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/linked/LinkedIdCreateGithubFragment.java
Enables Javascript for the github OAuth webView.
Enables Javascript in the webView used by the github OAuth 
This fixes #2080 
Runs OK, single line of code should not effect other areas
> Fix #2080 by adding Javascript 

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EditKeyFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvSubkeysFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/EditSubkeyDialogFragment.java
- OpenKeychain/src/main/res/values/strings.xml
This PR removes the "Move to Card" feature from the subkey edit UI. This is due to a number of reasons:
- as implemented, the operation invariably led to an NPE. from what I could see in the git history, this has been the case for a long time, so it's unlikely this feature was actually used
- beyond the crash, this would only work if the admin pin was set to 12345678, and we don't have a very good concept yet of what to do if this isn't true (see also #1844). this is not quite trivial since we only have three attempts at wrong pins. consequently, assuming it's the default first will use up one of these attempts, but assuming otherwise (which should rarely be the case) makes the operation as a whole much less user friendly.
- even if this had worked as intended, the feature would have been …
> remove "Move to Card" action from subkey edit ui

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpHelper.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysFileFragment.java
- OpenKeychain/src/main/res/values/strings.xml
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/PgpHelperTest.java
This PR adds some logic that attempts to reformat public key blocks read from the clipboard. It checks for patterns in the first twelve bits of encoded key data, so it makes more assumptions than previously about the structure of these blocks.
This allows recovering keys from arbitrary whitespace changes. It also drops ascii armor headers, but we never use those for public keys so that shouldn't be an issue.
Fixes #2161
Unit tests included
> Reformat public key blocks when loaded from clipboard

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenHelper.java
This commit reflects a [recent commit](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commitdiff;h=ff7ccd284c327a5b1c89603f157089177dac9d13) in GnuPG to fix incorrect encoding of data sent to a security token for the deciphering using ECC with large parameters (Brainpool 512 or NIST p521).
For large EC parameters (Brainpool 512 or NIST p521) the length of TLV encoded data for the decipher command is encoded on two bytes instead of one. It is actually systematically encoded on one byte in the existing code, which is wrong. This wrong encoding scheme, also present in GnuPG, as been [recently fixed](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commitdiff;h=ff7ccd284c327a5b1c89603f157089177dac9d13).
With large EC parameters (Brainpool 512 or NIST p521) the length of TLV …
> Fix EC decipher template

- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/provider/InteropTest.java
Change the license for the interoperability test runner
to Apache 2.0, matching standard Google open source practice.
> Update interop test license to Apache 2.0

- OpenKeychain/build.gradle
Updated support libraries and ran ./gradlew calculateChecksums
Compiles just fine. Deployment to test device apparently needs multidex.
> Update support libraries to 25.3.1 and update gradle-witness hashes

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/linked/resources/GithubResource.java
GitHub allows dash / minus characters in usernames (e.g. "wiktor-k" or
"open-keychain"). This change extends the regular expression to capture
this missing character.
It allows displaying Github Linked Identity resources that contain dash character.
It has not been tested at all. I imagine one character change will not break anything but if it's required I can setup the project and build it to see if it really works :)
> Accept dash character (-) in GitHub user names when checking for Gist URL

- OpenKeychain/src/main/res/xml/usb_device_filter.xml
I propose we disable unsupported USB devices for now until we properly support them.
I also worked on the [wiki page about supported tokens](https://github.com/open-keychain/open-keychain/wiki/Security-Tokens) which is now linked from our FAQ page: https://github.com/open-keychain/open-keychain.github.io/commit/53ee5c718af59897dec992ac606e1bd2de932416
> Disable unsupported USB tokens

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CertifyFingerprintFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/KeyFormattingUtils.java
The colorization of fingerprints never really provided a lot of benefits as only OpenKeychain implements this method and there exist better methods such as QR Code and SafeSlinger between two OpenKeychain apps.
In addition, the security of such a scheme is not easy to evaluate. An attacker may generate a partial pre-image considering similar looking colors.
> Remove colorization of fingerprints

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/dialog/RemoteDeduplicatePresenter.java
Upon dialog dismissal the view is set to null, consequently there is no view when the loader is reset as result of the activity being destroyed.
I found this since I based RemoteSelectAuthenticationKeyPresenter on RemoteDeduplicatePresenter.
Not tested in RemoteDeduplicatePresenter, but works in RemoteSelectAuthenticationKeyPresenter.
> Fix NPE upon dialog dismissal in RemoteDeduplicatePresenter

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/SshAuthenticationService.java
SshAuthenticationService
Use the specific error code for invalid algorithm instead of a generic error.
> Fix error handling in case of an unsupported algorithm parameter in

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/Constants.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnection.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenInfo.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/UsbConnectionDispatcher.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/UnsupportedUsbTokenException.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/UsbTransport.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/base/BaseSecurityTokenActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/res/values/strings.xml
- OpenKeychain/src/main/res/xml/experimental_preferences.xml
The previous approach to usb whitelisting (added in 0920d9757228930ddc44ae802b6a18fb0f4e96a1, removed again in 1f7c7f49d481efd8e59e08b3d23023e2fc92cf75) didn't actually work, since communication errors happened before the check was ever called. This PR adds a similar check, but much earlier in the procedure and in the UsbTransport only.
Not at all, so far :)
> Use different approach for whitelisting usb security tokens

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/Constants.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/ContactSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/KeyserverSyncAdapterService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
Hopefully fixes #1996
If the first time wizard is not finished or properly finished, the contacts sync notification will pop-up again and again because the service keeps re-enabling on application start.
#1996
> Do not re-enable contacts sync if first time wizard is not finished

- OpenKeychain/build.gradle
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/network/OkHttpClientFactory.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/network/TlsCertificatePinning.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/dialog/AddEditKeyserverDialogFragment.java
Removes the unused AndroidPinning dependency and refactors certificate pinning to work with OkHttp 3.9. The previously used method ``sslSocketFactory(SSLSocketFactory sslSocketFactory)`` is deprecated and ``sslSocketFactory(SSLSocketFactory sslSocketFactory, X509TrustManager trustManager)`` must be used in OkHttp's builder.
I basically followed the docs of these methods for implementation and tested all our keyservers.
> Remove unused AndroidPinning and refactor certificate pinning

- OpenKeychain/src/main/res/layout/create_key_start_fragment.xml
Disallow multiline in "USE SECURITY TOKEN" button title to avoid localized text clash with subtitle.
Added `android:singleLine="true"` to the TextView in `create_key_start_fragment.xml`
Fixes #2170 
Before:
After:
> Avoid localized text clash in create key start fragment

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/CachedPublicKeyRing.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/SshAuthenticationService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/dialog/KeyLoader.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/dialog/RemoteSelectAuthenticationKeyPresenter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/CertifyKeySpinner.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/SignKeySpinner.java
Make predicate names in KeychainProvider consistent and allow export of SSH public keys from keyrings with authentication subkey but without associated private key.
This allows for use cases where the user needs to copy the SSH public key blob of someone else (or of a keyring with secret key material on another device) manually into an app not using the sshauthentication-api (of which the implementation in OpenKeychain also supports export of SSH public keys for keyrings without private key with this PR) or a browser.
Works for me.
> Make predicate names in KeychainProvider consistent and allow export of SSH public keys without associated private key in keyring

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainApplication.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenInfo.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/CreateSecurityTokenWaitFragment.java
Use Constants.DEBUG instead of BuildConfig.DEBUG to allow debugging of release builds
Debugging a problem caused by ProGuard requires me building a release build but with logging enabled.
> Use Constants.DEBUG instead of BuildConfig.DEBUG

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/SaveKeyringResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/AutocryptPeerDataAccessObject.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainDatabase.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainExternalContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/AutocryptInteractor.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/KeychainExternalProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpServiceKeyIdExtractor.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/dialog/RemoteDeduplicatePresenter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/IdentityAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/KeySectionedListAdapter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/keyview/loader/IdentityLoader.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/keyview/presenter/IdentitiesPresenter.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/util/adapter/CursorAdapter.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/remote/KeychainExternalProviderTest.java
This PR changes the logic from behavior Autocrypt-circa-July to the shiny new Autocrypt 1.0. These changes should be compatible with current K-9, but I havn't done a lot of testing yet.
Still missing is a way to deal with "external" keys. I don't have a good plan for that yet. It might make sense to save a state similar to having received an autocrypt header when we see a signature by some key from an email address (careful with mailing lists though). There are a lot of variations to this concept, and it's actually not terribly important for now to get this 100% right. It does need to handle deduplication of keys though, that's broken right now and needs to be fixed.
> Autocrypt 1.0

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/CertifyOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/EditKeyOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/ImportOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeyRepository.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeyWritableRepository.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/LastUpdateInteractor.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/SettingsKeyserverFragment.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/provider/InteropTest.java
This adds a bunch of fixes for the "last updated" mechanism:
1) it actually doesn't forget the keyserver status when a key is saved (or updated) for some reason
2) when a key is certified and uploaded, it is remembered as such
> Last update fixes

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/OpenPgpCommandApduFactory.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/operations/PsoDecryptTokenOp.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnectionCompatTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/securitytoken/operations/PsoDecryptTokenOpTest.java
This is a different take on 1c8cc99c681a435254a1326949da33a88a532b57, sending the expected result size. It's not what the spec says, but it's what GnuPG does (if I had a nickel), so it should achieve good compatibility.
Related #2049 
Tests pending
> token: send expected result size as Le

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/SshAuthenticationService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ssh/signature/SshSignatureConverter.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/ssh/signature/SshSignatureConverterTest.java
[RFC8332](https://tools.ietf.org/html/rfc8332) defines new signature format identifier for RSA signatures with SHA256 & SHA512. Use those for correct SSH signature creation.
Works with ConnectBot.
Passes test.
> Use correct signature format identifier when creating SSH signatures for RSA with SHA256 & SHA512

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/BackupOperation.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ApiPendingIntentFactory.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/RemoteDisplayTransferCodeActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/BackupKeyringParcel.java
- OpenKeychain/src/main/res/layout/api_display_transfer_code.xml
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/BackupOperationTest.java
This PR builds on #2304, adding an API method that allows clients to generate the encrypted payload part of an Autocrypt Setup Message. This is a WIP at the moment, I'll push a related PR on K-9 soon.
> Add autocrypt key transfer api method

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
This change allows importing keys from NDEF tags that have fingerprint encoded as an `openpgp4fpr` URI when the application is in background.
After scanning a tag the `Import keys` activity is shown with results of the search for key fingerprint encoded in the tag.
Cheap NFC tags can be used as an alternative to barcodes when exchanging public keys. They can also be used as a business card, that, when scanned, will open OpenKeychain and look for the key.
Built a fdroid variant, OpenKeychain moved to background (by pressing Android Home key), prepared and scanned NDEF tag with a sample URI (`openpgp4fpr:73EE2314F65FA92EC2390D3A718C070100012282`). Import keys window is shown.
After scanning the tag only standard Import Keys window is shown.
- ✅ New feature (non-breaking change which adds …
> Add support for NDEF tags with `openpgp4fpr` URIs

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/Constants.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/CloudSearch.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/WebKeyDirectoryClient.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/network/OkHttpClientFactory.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/Preferences.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/WebKeyDirectoryUtil.java
- OpenKeychain/src/main/res/values/strings.xml
- OpenKeychain/src/main/res/xml/cloud_search_preferences.xml
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/util/WebKeyDirectoryUtilTest.java
This change allows handling Web Key Directory links by OpenKeychain (they always have scheme `https` and path starting with `/.well-known/openpgpkey/hu`).
This change also fixes two issues with WKD: 1) handling e-mails with leading/trailing spaces 2) following redirects on WKD links, just like gnupg does (some hosts like `kernel.org` use it). It also adds tests for WKD URL construction utilities.
This change completes support of WKD in #2270 and allows importing keys over WKD using links similarly to how Facebook or HKP links are handled.
Deployed debug build on a phone and tested links mentioned in #2270.
After clicking on a link.
> Extend WKD support to include WKD URLs

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/HkpKeyserverClient.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/KeyserverClient.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/processing/ImportKeysListCloudLoader.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/GetKeyResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/ImportKeysAdapter.java
- OpenKeychain/src/main/res/values/strings.xml
This updates the handling of key queries with hkp servers by trying to conform to [OpenPGP HKP](https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00).
Any feedback is welcome!
- Partly fixes #2061 as the handling of hkp server responses did not respect valid results as defined in [OpenPGP HKP](https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00), especially disrespecting empty field.
Tested with hkps://keys.mailvelope.com and default hkp servers.
> HKP server handling adopted to conform to draft-shaw-openpgp-hkp-00

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnection.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenInfo.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/CcidDescription.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/tpdu/T0ShortApduProtocol.java
This PR adds rudimentary support for T=0 protocol with short APDUs. Honestly, it took me a bit by surprise that this just worked :) since I didn't have to add changes for any of the actual differences between T=0 and T=1, like tpdu mapping and procedure bytes. But - I don't wan to complain too much, this seems to work now with just these few changes.
Fixes #2135
> Support Ledger Nano S

- OpenKeychain/src/main/res/values-v21/themes.xml
Instructs Android System UI to color the navigation bar dark when using dark theme. 
This avoids ugly white bars on dark theme.
Build and tested on device.
Before:
After (keys cleared):
> Color navigation bar dark when using dark theme

- OpenKeychain/build.gradle
- sshauthentication-api/build.gradle
Update android gradle plugin for sshauthentication-api to 3.1.3, same as OpenKeychain.
Fix whitespace.
Built & tested with TermBot.
> Update android gradle plugin for sshauthentication-api 

- OpenKeychain/src/main/AndroidManifest.xml
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/KeychainDatabase.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/AbstractDao.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/DatabaseBatchInteractor.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/DatabaseNotifyManager.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/KeyRepository.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/KeyWritableRepository.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/UserIdDao.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/model/Certification.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/model/KeyRingPublic.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/model/KeySignature.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/model/SubKey.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/model/UserPacket.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/operations/results/OperationResult.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainExternalContract.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/AutocryptInteractor.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/KeychainExternalProvider.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/KeyListFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvUserIdsFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/token/ManageSecurityTokenFragment.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/widget/CertListWidget.java
- OpenKeychain/src/main/sqldelight/org/sufficientlysecure/keychain/Certs.sq
- OpenKeychain/src/main/sqldelight/org/sufficientlysecure/keychain/KeyRingsPublic.sq
- OpenKeychain/src/main/sqldelight/org/sufficientlysecure/keychain/KeySignatures.sq
- OpenKeychain/src/main/sqldelight/org/sufficientlysecure/keychain/Keys.sq
- OpenKeychain/src/main/sqldelight/org/sufficientlysecure/keychain/UserPackets.sq
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/remote/KeychainExternalProviderTest.java
This is a follow-up to #2351. It does a couple of things:
- removes remaining functionality from KeychainProvider, specifically insert operations
- Uses MatrixCursor fed from DAOs instead of a temporary SQLite DB in KeychainExternalProvider
> Ditch keychain provider

- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/BackupOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/CertifyOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/operations/PromoteKeyOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/PgpEncryptDecryptTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/PgpKeyOperationTest.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/util/TestingUtils.java
Remove all usage of `genPassphrase` and use common, static passphrases instead. 
Fix https://github.com/open-keychain/open-keychain/issues/1881
Passes several test suite runs.
> WIP: Use static passphrases in tests

- gradle/wrapper/gradle-wrapper.properties
Update gradle wrapper to 4.9.
The [release notes](https://docs.gradle.org/4.9/release-notes.html) do not mention anything that should be relevant to us.
Test suite completes without error.
- ✅ update
> Update gradle wrapper to 4.9

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/PassphraseDialogActivity.java
I often use a hardware keyboard with my tablet.
Before:
When entering the password and pressing enter, by default the cursor moves to the next visible element in the ui.
Now: On enter the password will be confirmed, like with a software keyboard
> PassPhraseDialog: confirm password on enter key

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/CardCapabilities.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/OpenPgpCapabilities.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnection.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenInfo.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/UsbTransport.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenUtilsTest.java
This patch adds support for the Secalot hardware token, www.secalot.com.
Secalot supports OpenPGP Card specification version 2.1.1 with RSA keys up to 2048 bits.
Initialization with open-keychain is possible, card reset is not.
We want to be compatible with as many applications as possible.
The change was tested with a Secalot device connected to a Galaxy S8 phone with a USB-A to USB-C adapter. Card initialization, signing and encryption work.
Dear maintainers, if you want a device for future regression testing, can you please drop a message at hi@secalot.com with an address where to send, and we will send you one for free.
> Add Secalot hardware token support.

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/KeyRepository.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/dialog/RemoteSelectAuthenticationKeyActivity.java
- OpenKeychain/src/main/sqldelight/org/sufficientlysecure/keychain/Keys.sq
Presently the dialog lists all master keys, and keys without auth subkeys are not marked in any way. Selecting one of those via SSH authentication API will result in cryptic "Could not create description: null" message.
Ran a debug build of OpenKeychain in emulator, created 2 keys - one with auth subkey, and one without. Opened key selection dialog from termbot, there's only the key with auth subkey in the list.
> Make sure auth key selection dialog lists only keys with auth subkey available.

- OpenKeychain/src/main/res/values-es/strings.xml
Fix #2433
An empty CDATA field was responsible of crashing OpenKeychain on every attempt to add a key to an account in K9-Mail, but only if the system language is Spanish.
Fixes #2433
I'm sorry, I'm not able to compile and test the change, but it's very minimal and basically modified it accordingly to the rest of translations.
> Fix Spanish translation to resolve a crashing issue

- build.gradle
Trying to build OpenKeychain with Android Studio 3.4.1 I get the following error:
```
A problem occurred configuring project ':OpenKeychain'.
> Could not find support-media-compat.aar (com.android.support:support-media-compat:27.1.1).
Searched in the following locations:
https://jcenter.bintray.com/com/android/support/support-media-compat/27.1.1/support-media-compat-27.1.1.aar
```
I have no idea why this happens or why the order is important (yet).
[Gradle Userguide: dependency resolution](https://docs.gradle.org/current/userguide/userguide_single.html#sec:dependency_resolution)
Builds & works.
> Switch order of repositories, search Google Maven repo first

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/FileHelper.java
Fixing a crash when selecting some files for encryption (such as small text files or extensionless files).
Broadened exceptions caught when calling `DocumentsContract.getDocumentThumbnail`.
Android 8.0.0, security patch level June 1, 2019
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
at android.os.Parcel.readException(Parcel.java:1973)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
at …
```
> workaround for NullPointerException for some document thumbnails

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/WebKeyDirectoryClient.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/WebKeyDirectoryUtil.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/util/WebKeyDirectoryUtilTest.java
This change extends the WKD support with Advanced mode stated in
RFC Draft: draft-koch-openpgp-webkey-service-08 section 3.1
Advanced mode shall be queried first and use direct mode as fallback
this implements the design from the draft. 
Notice: This might change in future
versions of RFC Draft draft-koch-openpgp-webkey-service
Added advanced method advanced method URI lookup and previous 
direct mode as fallback. 
When bigger providers or WKD providers are available they would
probably go with advanced mode for custom domains. 
Key owners which cannot add .well-known folder on web service due
to services provider limitation needs an other method for publish keys
on WKD with subdomain openpgpkey a WKD provider or own http
server can be used.
Adding unit tests. Tested in emulator, WKD …
> Adding support for WKD Advanced method

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/MainActivity.java
- OpenKeychain/src/main/res/values/strings.xml
The navigation drawer gets a new entry labeled "Try Autocrypt Thunderbird".
A click calls an uri activity with "https://addons.thunderbird.net/en-US/thunderbird/addon/autocrypt/" as destination.
DrawerItem with name and blur icon and a bold typeface was added.
It helps users to get in touch with frictionless OpenPGP experience at Thunderbird.
Pixel 2 XL plugged in and run the app.
> Add an advertisement for autocrypt thunderbird plugin to navigation drawer

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/DecryptActivity.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/EncryptDecryptFragment.java
Move clipboard access from DecryptActivity to EncryptDecryptFragment since the clipboard access is only possible from a window in focus in Android 10.
Fix #2492 #2464 
Tested by encrypting & decrypting an example text fragment to & from the clipboard on an Android 10 device.
> Fix decryption from clipboard on Android 10

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/util/WebKeyDirectoryUtil.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/util/WebKeyDirectoryUtilTest.java
This change adds the l=LOCAL-PART query parameter to WKD URLs as
specified in RFC Draft: draft-koch-openpgp-webkey-service-09 section 3.1
since version 07.
The current code without this change does not work with WKD servers which expect the l=LOCAL-PART query parameter specified in the RFC Draft since version 07 to be present.
I ran the test functions in the WebKeyDirectoryUtilTest.
> Add query parameter to WKD URLs

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/KdfCalculator.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/KdfParameters.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/OpenPgpCapabilities.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnection.java
- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/securitytoken/KdfCalculatorTest.java
Implement password KDF as described in OpenPGP application specifications v3.3 chapter 4.3.2.
This fixes #2368.
OpenPGP application specifications v3.3 introduce the ability to send a repeatedly hashed and salted password instead of plaintext to a token.
Text encryption/decryption tested with a Nitrokey Start and a Yubikey with KDF enabled.
Backwards compatibility tested with a random card with KDF disabled.
> Implement password KDF

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/KdfParameters.java
The KDF-DO parser was missing a break statement, resulting in parsing a token with KDF ability, but having KDF disabled, as a token with KDF enabled, thus resulting in a Autovalue error upon trying to parse the KDF-DO returned by the token.
Fixes #2650
Not tested, since obviously correct :).
> Add missing break statement in KDF-DO parser

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/KdfParameters.java
The Autovalue builder of `KdfParameters` didn't initialize all members, thus leading to:
```
java.lang.IllegalStateException: Missing required properties: digestAlgorithm iterations saltPw1 saltPw2 saltPw3 hashUser hashAdmin
```
Fixes #2650, this time for good :slightly_smiling_face: 
Tested with a Yubikey 5 NFC, firmware version 5.2.7, with a Ed25519 primary key (SCA) and RSA-4096 encryption subkey, and KDF disabled.
> Fix KdfParameters builder

- .github/workflows/Android-CI-Espresso.yml
It prevents from 
>* What went wrong:
> Could not determine the dependencies of task ':extern:bouncycastle:test'.
>
> Task with path ':core:test' not found in project ':extern:bouncycastle'.
bouncycastle should test there own stuff in there repo
> Don't run BouncyCastle tests (make master work)

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/operations/PsoDecryptTokenOp.java
Fix ECDH decryption error using NIST curves: Invalid KEK
Decrypting using smart cards/tokens fails now due to "Invalid KEK". May fix #2516.
According to [Section 7 of RFC 6637](https://tools.ietf.org/html/rfc6637#section-7), the input of KDF should be the x portion instead of the encoding of the point.
Tested using smart cards.
- ✅ Bug fix
> Fix ECDH decryption error using NIST curves

- OpenKeychain/src/main/java/org/bouncycastle/openpgp/operator/jcajce/NfcSyncPGPContentSignerBuilder.java
- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/CanonicalizedSecretKey.java
A comment in bug #2677 notes that hashing should only be skipped when generating a signature for ssh authentication.
I have verified that ssh authentication still works with a yubikey 5c nfc and openssh/okc-agent as in #2662. I have also tested encrypting / signing files and text using the built-in functionality, and decrypting / verifying them both using the built-in functionality and GnuPG.
Fixes #2677
> Only skip hashing when creating an EDDSA authentication signature

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/SecurityTokenConnection.java
The PIN is cleared anyway when the Passphrase object holding the PIN is freed.
Commit c2bab8807e8b17f73dffbd17d5662453de631471 introduced clearing the admin PIN before it is being used.
Creating new keys was broken by c2bab8807e8b17f73dffbd17d5662453de631471.
Fixes https://github.com/open-keychain/open-keychain/issues/2684.
Tested with a Yubikey 5 NFC.
> Don't explicitly clear PIN when verifying admin PIN

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/keyimport/HkpKeyserverClient.java
Searching for keys on the default keyserver (keys.openpgp.org) yields no results.
Upon debug, it looks like the answer from the server contains Windows-style EOL, which is incorrectly parsed by the current regexps.
Fixes bug #2690 
> Fix parsing of EOL in keyserver answer

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/operations/PsoDecryptTokenOp.java
Fix #2681 
From rfc6637#section-7: The input of KDF should be the x portion of the point.
However, the result of ECDH can be expressed in two formats: compressed and uncompressed. GnuPG can deal with both cases but before Open-Keychain 5.7, it only supports the compressed format and after 5.7 (since commit e82fb82) it only supports the uncompressed format.
This PR first checks if the ECDH is the compressed format and then extracts the x portion accordingly.
See #2681 
Tested on SmartPGP, which has the same behavior as YubiKey.
> fix the compatibility of compressed and uncompressed format in ECDH

- OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/SplitUserIdTest.java
Updates `openpgp-api` to its latest revision and add a backing test for the changes.
Fixes #2579
Unit test is included
> Bump openpgp-api and add a test for TLD-less email

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/PassphraseDialogActivity.java
In the current implementation of the lifecycle of the Passphrase dialog, the dialog gets dismissed and re-created in onPause and onResumeFragments. For the user, it seems as if the input is cleared if he switches apps, turns phone to standby or uses autofill (e.g. password managers). This PR modifies the lifecylce logic, such that the dialog does not get dismissed in this occations.
The current implementation made it impossible to switch to another app to copy the password for a key; one had to copy it before opening the dialog.
Using the autofill feature (implemented by most password managers) was also not possible.
This change fixes #2449 / also fixes #2828
Only PassphraseDialogActivity.java has been modified. I opened the dialog (select key > export key) and tested using autofill, …
> Improve PassphraseDialog lifecycle logic

- OpenKeychain/src/main/res/values-night/styles.xml
- OpenKeychain/src/main/res/values/styles.xml
I adjusted the transfer code color to white (#FFF) in dark mode while keeping it black (#000) in light mode.
The transfer code is barely visible in dark mode.
Switched the system theme from light to dark mode.
> Fix: transfer code text color in dark mode

- OpenKeychain/src/main/java/org/sufficientlysecure/keychain/daos/UserIdDao.java
after upgrade of sqlitedb library sqldelight in commit 5d84bd838744f63d46d5a08110bad13b5192ae6a the method getUidStatusByEmailLike may suddenly raise a NullPointerException. This fix attempts to restore the prior behavior or simply returning null.
It attempts to fix Issue #2881.
I did not yet test this change, this is merely a proposal, as described in Issue #2881.
> 🐛fix Issue #2881: avoid NullPointerException in selectUserIdStatusByEmailLike

- OpenKeychain/src/main/res/layout/add_email_dialog.xml
Fixes a crash when attempting to add an additional email address while creating a key.
The app crashed with the following stack trace:
```text
java.lang.ClassCastException: androidx.appcompat.widget.AppCompatTextView cannot be cast to androidx.appcompat.widget.AppCompatEditText
at org.sufficientlysecure.keychain.ui.dialog.AddEmailDialogFragment.onCreateDialog(AddEmailDialogFragment.java:83)
at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:644)
at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:558)
at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1654)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentS …
```
> Fix crash when adding additional email address while creating a key
